### ISSUE TITLE
niet zo responsive

### ISSUE THREAD

**Issue by Theo-denBlanken** [RegilioSpee/jQuery-helden#2]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c

@media screen and (min-width: 800px) {
  main {
    grid-template-columns: 1fr 1fr;
  }
}
@media screen and (min-width: 1000px) {
  main {
    grid-template-columns: 1fr 1fr;
  }
} 
```

URL: https://github.com/RegilioSpee/jQuery-helden/blob/master/jQuery/css/helden.css

Feedback: blijft 2 koloms[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"5a975a0c632fc7e28c213f874024d7fc0e68f2e6","path":"jQuery/css/helden.css","reviewer":"Theo-denBlanken"}')

**Comment by RegilioSpee** [comment]
fractions aangepast in de css
