### ISSUE TITLE
teskten niet leesbar

### ISSUE THREAD

**Issue by Theo-denBlanken** [RegilioSpee/jQuery-helden#4]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/RegilioSpee/jQuery-helden/blob/master/

Feedback: zwart op zwarte achtrgrond[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by RegilioSpee** [comment]
tekst wit gemaakt
